### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by deluxhun** [unencouraged/Xenforo-Cheat-Loader#4]
Hy i get this message when i logging in "Internal error, contact staff"

**Comment by deluxhun** [comment]
I think is problem with hwid..but i dont mean what is the problem

**Comment by unencouraged** [comment]
issue with ur website probably. replace that line with the commented line next to it and that's ur error.


replace
MessageBox.Show("Internal error, contact staff");
with
MessageBox.Show(ex.Message);

it will probably be "internal server error" and its doing that because you aren't sending a user agent with your request.

**Comment by deluxhun** [comment]
1>C:\Users\DeLUX\Desktop\Xenforo-Cheat-Loader-master\Loader Files\Loader\Form1.cs(182,33,182,35): error CS0103: The name 'ex' does not exist in the current context

**Comment by deluxhun** [comment]
![image](https://user-images.githubusercontent.com/45321565/115436371-33a93800-a20b-11eb-8024-cb3f6d869a0e.png)

**Comment by unencouraged** [comment]
its not a hwid issue

change catch (Exception)

to catch (Exception ex)

**Comment by deluxhun** [comment]
![image](https://user-images.githubusercontent.com/45321565/115437400-69025580-a20c-11eb-927c-211febe52092.png)

Localhost error?

**Comment by deluxhun** [comment]
Its problem with hwid in sql bcs if i delete it i can register new account but if i take back hwid i cant ragister

**Comment by deluxhun** [comment]
Can u help me little?

**Comment by deluxhun** [comment]
XF\Db\Exception: MySQL query error [1364]: Field 'hwid' doesn't have a default value in src/XF/Db/AbstractStatement.php at line 228
XF\Db\AbstractStatement->getException() in src/XF/Db/Mysqli/Statement.php at line 196
XF\Db\Mysqli\Statement->getException() in src/XF/Db/Mysqli/Statement.php at line 77
XF\Db\Mysqli\Statement->execute() in src/XF/Db/AbstractAdapter.php at line 94
XF\Db\AbstractAdapter->query() in src/XF/Db/AbstractAdapter.php at line 218
XF\Db\AbstractAdapter->insert() in src/XF/Mvc/Entity/Entity.php at line 1510
XF\Mvc\Entity\Entity->_saveToSource() in src/XF/Mvc/Entity/Entity.php at line 1242
XF\Mvc\Entity\Entity->save() in src/XF/Install/Helper.php at line 379
XF\Install\Helper->createInitialUser() in src/XF/Install/Controller/Install.php at line 239
XF\Install\Controller\Install->actionStep3b() in src/XF/Mvc/Dispatcher.php at line 350
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 257
XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2326
XF\App->run() in src/XF.php at line 488
XF::runApp() in install/index.php at line 14

**Comment by unencouraged** [comment]
500 internal server error.
send a user agent with your request.

also in "Field 'hwid' doesn't have a default value" it literally tells you the problem. (you didnt set a default to the hwid column, do that.)

**Comment by deluxhun** [comment]
And how can i fix 500error?

**Comment by deluxhun** [comment]
Maybe htaccess file is bad

**Comment by deluxhun** [comment]
I dont know what is the problem..

**Comment by deluxhun** [comment]
Im using xf 2,2,4

**Comment by unencouraged** [comment]
i've told you the solution to 500 internal server error twice.

if you cant fix it you shouldn't even be thinking about running a cheat
