### ISSUE TITLE
Info.php not working?

### ISSUE THREAD

**Issue by RoleXzD** [unencouraged/Xenforo-Cheat-Loader#5]
Hello! I Uploaded All Files I did all Even tried watching some tutorials to get the loader to work. But I Got no Idea. My Info.php version is set the same as the Loader's but it says on "login" text " please update loader " I Tried Opening Info.php myself but it says:

This page isn’t working
mywebsite is currently unable to handle this request.

HTTP ERROR 500

**Comment by unencouraged** [comment]
https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-debugger
