### ISSUE TITLE
Info.php Not Loader issue

### ISSUE THREAD

**Issue by RoleXzD** [unencouraged/Xenforo-Cheat-Loader#6]
Hello, AGAIN beacsue u told me how to debug even if i was already. My issue is info.php beacuse it dosent work
Any Help on fixing Info.php? beacuse this is the error that apprears if i try to see it myself.
![image](https://user-images.githubusercontent.com/79577351/141412738-b97a8575-3955-4b01-85ba-9cc238269f9f.png)

( Only info.php doesnt work idk why )_

**Comment by unencouraged** [comment]
you aren't showing any error logs and i am not the person who made znix panel.

you are probably forgetting something here:
https://github.com/znixbtw/panel-v2#installation

**Comment by RoleXzD** [comment]
Isnt this a xenforo loader? What Does Znix Panel v2 Have to do with xenoforo, anyways. what version of xenforo do i need>?

**Comment by unencouraged** [comment]
whatever the latest version is.
you also haven't showed me any error so i can't help you.
in the same folder as info.php there should be a file called 'error_log' send the latest one from info.php
